language: r
sudo: false
cache: packages

matrix:
  include:
    - node_js: node
      cache:
        directories:
          - node_modules
    - r: oldrel
    - r: release
      after_success:
        - Rscript -e 'covr::codecov()'