export const APP_TIMER_START = 'APP_TIMER_START'
export const APP_TIMER_TICK = 'APP_TIMER_TICK'
export const APP_SET_TOUCH_CAPABLE = 'APP_SET_TOUCH_CAPABLE'

export const STOCKS_SUBSCRIBE = 'STOCKS_SUBSCRIBE'
export const STOCKS_SET_DATA = 'STOCKS_SET_DATA'
